spring.application.name=SpringSecurityApp

spring.datasource.url=jdbc:mysql://localhost:3306/security-app?useSSL=false
spring.datasource.username=root
spring.datasource.password=84K@5955e
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql

#security configs
#spring.security.user.name=ketan
#spring.security.user.password=ketan

jwt.secretKey = q8w1er2tyhnb3gfv47cdsxzuio4lmafd6ghghjy457ty89sv3khfjd273svdsfg